_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 2
                - 3
                - 55
            "2":
                - 1
                - 2
                - 3
                - 55
            "3":
                - 14
                - 23
                - 35
                - 55
            "4": 3.10.16
            "5": 0.19.3
            "8":
                - 3
                - 5
            "12": 0.19.3
            "13": windows-amd64
